# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - gofmt
    - goimports
    - misspell
    - gocritic
    - revive
    - copyloopvar
  # Temporarily disabled due to existing issues:
  # - errcheck (many unchecked errors)
  # - gosimple (S1009 nil check issues)
  # - unused (unused fields/functions)
  # - unconvert (unnecessary conversions)

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: hypervisor
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: increment-decrement
      - name: var-naming
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf

issues:
  exclude-rules:
    - path: pkg/compute/libvirt/
      text: "SA1019"  # Allow deprecated libvirt APIs if needed
    # Allow deprecated grpc.Dial for now
    - text: "SA1019.*grpc\\.Dial"
      linters:
        - staticcheck
    # Allow stuttering type names for now
    - text: "stutters"
      linters:
        - revive
    # Exclude gocritic style suggestions temporarily
    - text: "hugeParam|paramTypeCombine|ifElseChain|nestingReduce|octalLiteral"
      linters:
        - gocritic
  exclude-dirs:
    - api/gen  # Generated code
